commerce_product.commerce_product_variation_type.*.third_party.commerce_license:
  type: mapping
  label: 'License settings'
  mapping:
    license_types:
      type: sequence
      label: 'License types allowed with this product variation'
    activate_on_place:
      type: boolean
      label: 'Whether to activate a license when the order is placed'

views.field.commerce_license__entity_label:
  type: views.field.entity_label
