# Schema for the configuration files of the age_field_formatter module.

field.formatter.settings.age_field_formatter:
  type: mapping
  label: 'Age field formatter display format settings'
  mapping:
    age_format:
      type: string
      label: 'Date/age format'
    year_suffix:
      type: checkbox
      label: 'Year suffix'
