module:
  acquia_connector: 0
  address: 0
  admin_toolbar: 0
  age_field_formatter: 0
  aggregator: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  comment: 0
  commerce: 0
  commerce_cart: 0
  commerce_checkout: 0
  commerce_license: 0
  commerce_log: 0
  commerce_order: 0
  commerce_payment: 0
  commerce_price: 0
  commerce_product: 0
  commerce_store: 0
  config: 0
  config_filter: 0
  config_split: 0
  config_translation: 0
  contact: 0
  content_access: 0
  content_sync: 0
  content_translation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  drupalportugal_custom: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_toolbar: 0
  google_analytics: 0
  help: 0
  image: 0
  inline_entity_form: 0
  interval: 0
  language: 0
  languagefield: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  memcache: 0
  memcache_admin: 0
  menu_ui: 0
  metatag: 0
  metatag_dc: 0
  metatag_dc_advanced: 0
  metatag_open_graph: 0
  metatag_open_graph_products: 0
  metatag_verification: 0
  metatag_views: 0
  name: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pathauto: 0
  profile: 0
  quickedit: 0
  recaptcha: 0
  recurring_period: 0
  redirect: 0
  redirect_404: 0
  search: 0
  serialization: 0
  shortcut: 0
  state_machine: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  upgrade_status: 0
  user: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  ds: 1
  menu_link_content: 1
  webform_bootstrap: 1
  ds_extras: 2
  views: 10
  standard: 1000
  eu_cookie_compliance: 1001
theme:
  seven: 0
  bootstrap_barrio: 0
  drupalpt: 0
  claro: 0
  gin: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: pt-pt
