general_settings:
  radio_behavior: simples
  context_lines_leading: 1
  context_lines_trailing: 1
  revision_pager_limit: 50
  layout_plugins:
    split_fields:
      enabled: true
    unified_fields:
      enabled: true
    visual_inline:
      enabled: true
  visual_inline_theme: default
_core:
  default_config_hash: 2GE7UJUi0iGBPVb9DkGqN4bHjIsphvlb2DM8a-uej4s
langcode: pt-pt
