examples:
  -
    title: Mr
    given: Joe
    middle: 'John Peter Mark'
    family: Doe
    generational: Jnr.
    credentials: 'B.Sc., Ph.D.'
    preferred: Joe
    alternative: 'Lorem ipsum dolor'
  -
    title: ''
    given: JOAN
    middle: SUE
    family: DOE
    generational: ''
    credentials: ''
  -
    title: ''
    given: Prince
    middle: ''
    family: ''
    generational: ''
    credentials: ''
langcode: pt-pt
