component_required_marker: '*'
default_format: ((((t+ig)+im)+if)+is)+jc
sep1: ' '
sep2: ', '
sep3: ''
user_preferred: field_user_name_fullname
_core:
  default_config_hash: JCsvMkZ6JYCJ99YViyi8ie9Pf46l5eDF3rX01kl4g2A
langcode: pt-pt
