label: Carts
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
      fields:
        commerce_order_bulk_form:
          action_title: 'With selection'
        type:
          label: Type
          separator: ', '
        store_id:
          label: Store
          separator: ', '
        uid:
          label: Customer
          separator: ', '
        mail:
          label: Email
          separator: ', '
        total_price__number:
          label: Total
          separator: ', '
        changed:
          label: Updated
          separator: ', '
        operations:
          label: Operations
      filters:
        type:
          expose:
            label: Type
      title: Carts
      empty:
        area_text_custom:
          content: 'No orders available.'
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Carts
