settings:
  default_submit_button_label: Enviar
  default_reset_button_label: Reset
  default_wizard_confirmation_label: Concluída
  default_preview_next_button_label: Pré-visualização
  default_preview_label: Pré-visualização
  dialog_options:
    narrow:
      title: Estreito
    normal:
      title: Normal
    wide:
      title: Largo
element:
  default_more_title: Mais
mail:
  default_from_name: '[user:display-name]'
