display:
  default:
    display_title: Principal
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Descendente
      pager:
        options:
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
          tags:
            next: 'Seguinte ›'
      title: Fontes
  feed_1:
    display_title: Feed
    display_options:
      title: 'feed OPML'
  page_1:
    display_title: Página
    display_options:
      menu:
        title: Fontes
