label: Ficheiros
display:
  default:
    display_title: Principal
    display_options:
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Descendente
      pager:
        options:
          tags:
            next: 'Seguinte ›'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      fields:
        filename:
          label: Nome
        filemime:
          label: 'Tipo MIME'
        filesize:
          label: Tamanho
        status:
          label: Estado
        created:
          label: 'Data de carregamento'
        changed:
          label: 'Data alterada'
        count:
          label: 'Usado em'
      filters:
        filename:
          expose:
            label: 'Nome do ficheiro'
        filemime:
          expose:
            label: 'Tipo MIME'
        status:
          expose:
            label: Estado
      title: Ficheiros
      empty:
        area_text_custom:
          content: 'Sem ficheiros disponíveis.'
  page_1:
    display_options:
      menu:
        title: Ficheiros
  page_2:
    display_options:
      pager:
        options:
          tags:
            next: 'Seguinte ›'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      fields:
        entity_label:
          label: Entidade
        type:
          label: 'Tipo de entidade'
        count:
          label: 'Nº de Utilizações'
      arguments:
        fid:
          exception:
            title: Todos
