display:
  default:
    display_title: Principal
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Descendente
      filters:
        access:
          expose:
            label: 'Último acesso'
            description: 'Um utilizador é considerado "ligado" por este intervalo de tempo, após ter visualizado uma página pela última vez.'
      title: 'Utilizadores ligados'
  who_s_online_block:
    display_title: 'Utilizadores ligados'
    display_options:
      block_description: 'Utilizadores ligados'
