label: 'Biblioteca de blocos personalizados'
display:
  default:
    display_title: Principal
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Descendente
      pager:
        options:
          tags:
            next: 'Seguinte ›'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      fields:
        info:
          label: 'Descrição do bloco'
        type:
          label: 'Tipo Bloco'
        changed:
          label: Atualizado
        operations:
          label: Operações
      filters:
        info:
          expose:
            label: 'Descrição do bloco'
        type:
          expose:
            label: 'Tipo Bloco'
      title: 'Biblioteca de blocos personalizados'
  page_1:
    display_title: Página
    display_options:
      menu:
        title: 'Biblioteca de blocos personalizados'
