label: 'A página inicial'
description: 'Todo o conteúdo promovido para a primeira página.'
display:
  default:
    display_options:
      empty:
        area_text_custom:
          content: 'Ainda não foi criado nenhum conteúdo para a página inicial.'
        title:
          title: 'Bem-vindo a [site:name]'
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Descendente
      pager:
        options:
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
          tags:
            previous: '‹ Previous'
            next: 'Seguinte ›'
            first: '« First'
            last: 'Last »'
    display_title: Principal
  feed_1:
    display_title: Feed
  page_1:
    display_title: Página
